const places = [
  {
    name: "Cox's Bazer",
    country: "Bangladesh",
    img: "https://i.ibb.co/2hmXwyg/coxbazar-sq-1-png.jpg",
    price: "380",
    duration: "3",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Forest Adventure",
    country: "China",
    img: "https://i.ibb.co/0Zym1vm/khagrachori-sq-1-png.jpg",
    price: "780",
    duration: "4",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "KayKing Thailand",
    country: "Thailand",
    img: "https://i.ibb.co/kK1JtMz/sentmartin-sq-1-png.jpg",
    price: "690",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Wondering Cuba",
    country: "Cuba",
    img: "https://i.ibb.co/8KhjTvt/sajek-squre-1-png.jpg",
    price: "590",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Discover Costa-Rica",
    country: "Costarica",
    img: "https://i.ibb.co/m9218jN/Patenga-sq-1.jpg",
    price: "690",
    duration:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    description: "",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Beach in February",
    country: "California",
    img: "https://i.ibb.co/V9rXdt2/coxbazar-sq-1-png.jpg",
    price: "780",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Cox's Bazer",
    country: "Bangladesh",
    img: "https://i.ibb.co/2hmXwyg/coxbazar-sq-1-png.jpg",
    price: "380",
    duration: "3",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Forest Adventure",
    country: "China",
    img: "https://i.ibb.co/0Zym1vm/khagrachori-sq-1-png.jpg",
    price: "780",
    duration: "4",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "KayKing Thailand",
    country: "Thailand",
    img: "https://i.ibb.co/kK1JtMz/sentmartin-sq-1-png.jpg",
    price: "690",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Wondering Cuba",
    country: "Cuba",
    img: "https://i.ibb.co/8KhjTvt/sajek-squre-1-png.jpg",
    price: "590",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Discover Costa-Rica",
    country: "Costarica",
    img: "https://i.ibb.co/m9218jN/Patenga-sq-1.jpg",
    price: "690",
    duration:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    description: "",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Beach in February",
    country: "California",
    img: "https://i.ibb.co/V9rXdt2/coxbazar-sq-1-png.jpg",
    price: "780",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Cox's Bazer",
    country: "Bangladesh",
    img: "https://i.ibb.co/2hmXwyg/coxbazar-sq-1-png.jpg",
    price: "380",
    duration: "3",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Forest Adventure",
    country: "China",
    img: "https://i.ibb.co/0Zym1vm/khagrachori-sq-1-png.jpg",
    price: "780",
    duration: "4",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "KayKing Thailand",
    country: "Thailand",
    img: "https://i.ibb.co/kK1JtMz/sentmartin-sq-1-png.jpg",
    price: "690",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Wondering Cuba",
    country: "Cuba",
    img: "https://i.ibb.co/8KhjTvt/sajek-squre-1-png.jpg",
    price: "590",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Discover Costa-Rica",
    country: "Costarica",
    img: "https://i.ibb.co/m9218jN/Patenga-sq-1.jpg",
    price: "690",
    duration:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    description: "",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Beach in February",
    country: "California",
    img: "https://i.ibb.co/V9rXdt2/coxbazar-sq-1-png.jpg",
    price: "780",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Cox's Bazer",
    country: "Bangladesh",
    img: "https://i.ibb.co/2hmXwyg/coxbazar-sq-1-png.jpg",
    price: "380",
    duration: "3",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Forest Adventure",
    country: "China",
    img: "https://i.ibb.co/0Zym1vm/khagrachori-sq-1-png.jpg",
    price: "780",
    duration: "4",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "KayKing Thailand",
    country: "Thailand",
    img: "https://i.ibb.co/kK1JtMz/sentmartin-sq-1-png.jpg",
    price: "690",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Wondering Cuba",
    country: "Cuba",
    img: "https://i.ibb.co/8KhjTvt/sajek-squre-1-png.jpg",
    price: "590",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Discover Costa-Rica",
    country: "Costarica",
    img: "https://i.ibb.co/m9218jN/Patenga-sq-1.jpg",
    price: "690",
    duration:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    description: "",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Beach in February",
    country: "California",
    img: "https://i.ibb.co/V9rXdt2/coxbazar-sq-1-png.jpg",
    price: "780",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Cox's Bazer",
    country: "Bangladesh",
    img: "https://i.ibb.co/2hmXwyg/coxbazar-sq-1-png.jpg",
    price: "380",
    duration: "3",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Forest Adventure",
    country: "China",
    img: "https://i.ibb.co/0Zym1vm/khagrachori-sq-1-png.jpg",
    price: "780",
    duration: "4",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "KayKing Thailand",
    country: "Thailand",
    img: "https://i.ibb.co/kK1JtMz/sentmartin-sq-1-png.jpg",
    price: "690",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Wondering Cuba",
    country: "Cuba",
    img: "https://i.ibb.co/8KhjTvt/sajek-squre-1-png.jpg",
    price: "590",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Discover Costa-Rica",
    country: "Costarica",
    img: "https://i.ibb.co/m9218jN/Patenga-sq-1.jpg",
    price: "690",
    duration:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    description: "",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
  {
    name: "Beach in February",
    country: "California",
    img: "https://i.ibb.co/V9rXdt2/coxbazar-sq-1-png.jpg",
    price: "780",
    duration: "",
    description:
      "An adventure is an exciting experience or undertaking that is typically bold, sometimes risky. Adventures may be activities with some potential for physical danger such as traveling, exploring, skydiving, mountain climbing, scuba diving, river rafting or participating in extreme sports.",
    gallery: {
      img1: "",
      img2: "",
      img3: "",
      img4: "",
      img5: "",
    },
  },
];
